### ISSUE TITLE
Feature:I wonder I need a linux version of monodraw.

### ISSUE THREAD

**Issue by BruceWind** [helftone/monodraw-snippets#1]
Hi,bro.

Monodraw is a best app I have ever wanted. But I am used to using ubuntu. I dont like writing codes on mac or windows.You know that there is no linux verions. And then I will purchase a LICENSE of linux vesion.
Pls develop a linux version, I think it will make you gain more benefit.
pls help me.
thanks a lot.

**Comment by mikeyjoel** [comment]
Agree. Build a linux version :)

**Comment by irmoktran** [comment]
Someone that need Monodraw for linux here

**Comment by jozuenoon** [comment]
Would certainly buy if can share the license cross linux and mac 👍
